version: "3"

services:
      
    front:
        container_name: "front_ReactJs"
        build: ./front/
        ports:
            - "80:3000"
        volumes:
            - ./front/:/root/app/
        stdin_open: true
        tty: true
        restart: always
        environment:
            - CHOKIDAR_USEPOLLING=true

    front_test:
        container_name: "front_test"
        build: 
            context: ./front/
            dockerfile: Dockerfile_test
        ports:
            - "81:3000"
        volumes:
            - ./front/:/root/app/
        stdin_open: true
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true
    back:
        container_name: "back_ExpressJS"
        build: ./back/
        ports:
        - "8000:8000"
        volumes:
            - ./back/:/app/
        environment:
            WAIT_HOSTS: mongodb:27017
        expose: 
        - "8000"
        depends_on:
            - mongodb
        links:
            - mongodb
        tty: true
        restart: always
    back_test:
        container_name: "back_test"
        build: 
            context: ./back/
            dockerfile: Dockerfile_test
        ports:
        - "8001:8000"
        volumes:
            - ./back/:/app/
        environment:
            WAIT_HOSTS: mongodb:27017
        expose: 
        - "8001"
        depends_on:
            - mongodb
        links:
            - mongodb
        tty: true
    mongodb:
        image: bitnami/mongodb:latest
        container_name: "mongodb"
        environment:
            - MONGODB_ROOT_USERNAME=root
            - MONGODB_ROOT_PASSWORD=root
            - MONGODB_USERNAME=devapi
            - MONGODB_PASSWORD=devapi
            - MONGODB_DATABASE=t-web-api
            - MONGODB_PRIMARY_PORT_NUMBER=27017
            - Mo
        volumes:
            - 'mongodb_data:/bitnami/mongodb'
        ports:
            - "27017:27017"
        restart: always           
volumes:
    mongodb_data:
